upstream php-backend {
    server nextcloud:9000;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    client_max_body_size 10G;
    client_body_timeout 3600s;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
    }

    location ~ \.php(?:$|/) {
        fastcgi_pass php-backend;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ \.(?:jpg|jpeg|gif|bmp|webp|png|ico|cur|gz|svg|svgz|mp4|mp3|ogg|ogv|webm|htc)$ {
        expires 30d;
        access_log off;
    }

    location ~ \.(?:css|js|eot|ttf|woff|woff2)$ {
        expires 7d;
        access_log off;
    }

    location /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav/;
    }

    location /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav/;
    }
}